# Generated by Django 4.0.4 on 2022-05-20 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('release_date', models.IntegerField()),
                ('author_name', models.CharField(max_length=25)),
                ('author_last_name', models.CharField(max_length=50)),
                ('genre', models.ManyToManyField(related_name='novella', to='manga.genre')),
            ],
            options={
                'verbose_name': 'Novella',
                'verbose_name_plural': 'Novella',
            },
        ),
        migrations.CreateModel(
            name='NovellaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='novella')),
                ('novella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='manga.novella')),
            ],
        ),
    ]
