# Generated by Django 3.2.9 on 2022-05-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='novella',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
